### ISSUE TITLE
打开报错

### ISSUE THREAD

**Issue by niyade518** [OriX6/liveRecordAuto#1]
![image](https://github.com/OriX6/liveRecordAuto/assets/68718314/124dbe71-9746-4371-8c60-75026d2698ff)

**Comment by OriX6** [comment]
> ![image](https://user-images.githubusercontent.com/68718314/264911085-124dbe71-9746-4371-8c60-75026d2698ff.png)
这是软件初始化时，创建基本保存目录的（默认取剩余空间最大的盘）~ 看起来你的E盘好像无法访问 检 检查一下权限呢？

**Comment by Cyiming** [comment]
> > ![image](https://user-images.githubusercontent.com/68718314/264911085-124dbe71-9746-4371-8c60-75026d2698ff.png)
> > 这是软件初始化时，创建基本保存目录的（默认取剩余空间最大的盘）~ 看起来你的E盘好像无法访问 你的E盘应该是什么东西的映射吧？ 没有创建文件夹的权限 所以报错了

我也这个情况 默认选取的是映射盘 能不能让用户手动选择安装地址
