### ISSUE TITLE
向作者请教使用中的一个问题

### ISSUE THREAD

**Issue by chenpingan23** [OriX6/liveRecordAuto#102]
提前设定好了直播监控，要是电脑提前进入睡眠并熄屏了，后面直播开始后还能录制吗？在设定监控后电脑需要一直保持亮屏吗？期待作者的回复，谢谢

**Comment by OriX6** [comment]
> 提前设定好了直播监控，要是电脑提前进入睡眠并熄屏了，后面直播开始后还能录制吗？在设定监控后电脑需要一直保持亮屏吗？期待作者的回复，谢谢

睡眠会断网+休眠  断网和磁盘休眠 那肯定录制不了了
锁屏是正常的
