### ISSUE TITLE
抖音录制的会分段怎么办

### ISSUE THREAD

**Issue by Gh-37** [OriX6/liveRecordAuto#11]

**Comment by OriX6** [comment]
> _No description provided._

如果你说的是会细碎小段是现有bug，参考之前的回复，将在本月更新修复掉

**Comment by t1xhop** [comment]
> > _No description provided._
> 
> 如果你说的是会细碎小段是现有bug，参考之前的回复，将在本月更新修复掉

非常感谢你的软件。有个小问题不知道你遇到过吗。就是录制完，主播下播后，（仍然显示录制中）软件不关闭它。第二天主播开播了，但是软件并没没有开始录制。

**Comment by MichealShin** [comment]
我估计是网络问题导致的，我准备换条网络，也希望hub主能提供个其他架构的能部署在我的ubuntu服务器上，windows服务器不太常见

**Comment by OriX6** [comment]
问题已经在1.0.7 修复 故 close

**Comment by OriX6** [comment]
> 我估计是网络问题导致的，我准备换条网络，也希望hub主能提供个其他架构的能部署在我的ubuntu服务器上，windows服务器不太常见

其他架构的话 这个我得考虑一下 先加入todo中 本issue close
