### ISSUE TITLE
功能需求/改进

### ISSUE THREAD

**Issue by shensizhebobo** [OriX6/liveRecordAuto#13]
> **1、提供格式选项3选1设置：**
①默认TS格式、②自动转MP4（自动删除TS）、③TS+MP4二者均保留；
这样最大程度保证数据安全。

> **2、增加截断动能：**
①后台设置里，添加“满xx分钟”自动分段选项，以防止录制时间太长文件过大，减少数据出错风险。
②也可以考虑在前台添加手动截断功能。

> **3、定时录制场景：**
场景描述：我经常录制日出和日落，但一些景区直播号（24小时监控直播流那种），所以不方便对他们开启“自动监控”，否则24小时在不停录制。如果能针对每个主播，自定义主要监控时间段就比较方便。比如自定义早上5:30~7:00时间段内监控并录制，超出此时间不监控不录制，除非再次改变监控时间段。
而且这样应该减少了对直播平台的数据需求，是否会有利于不被封IP。

> **4、一键开启：**
添加一键开启/停止“监控、录制”功能。
场景描述：关注的主播比较多，前一天的“监控状态”有的开启有的关闭，需要一个个手动调整比较繁琐。如果有一键功能，会方便不少。

> **5、停止录制的逻辑：**
若直播仍在继续，手动“停止录制”后，应自动关闭“监控中”成灰色。
目前遇到的情况是：手动“停止录制”后，即使我同时关闭了“监控”按钮，一会又自动开启了录制，需要再手动“停止录制”一次。

**Comment by OriX6** [comment]
> > **1、提供格式选项3选1设置：**
> > ①默认TS格式、②自动转MP4（自动删除TS）、③TS+MP4二者均保留；
> > 这样最大程度保证数据安全。
> 
> > **2、增加截断动能：**
> > ①后台设置里，添加“满xx分钟”自动分段选项，以防止录制时间太长文件过大，减少数据出错风险。
> > ②也可以考虑在前台添加手动截断功能。
> 
> > **3、定时录制场景：**
> > 场景描述：我经常录制日出和日落，但一些景区直播号（24小时监控直播流那种），所以不方便对他们开启“自动监控”，否则24小时在不停录制。如果能针对每个主播，自定义主要监控时间段就比较方便。比如自定义早上5:30~7:00时间段内监控并录制，超出此时间不监控不录制，除非再次改变监控时间段。
> > 而且这样应该减少了对直播平台的数据需求，是否会有利于不被封IP。
> 
> > **4、一键开启：**
> > 添加一键开启/停止“监控、录制”功能。
> > 场景描述：关注的主播比较多，前一天的“监控状态”有的开启有的关闭，需要一个个手动调整比较繁琐。如果有一键功能，会方便不少。
> 
> > **5、停止录制的逻辑：**
> > 若直播仍在继续，手动“停止录制”后，应自动关闭“监控中”成灰色。
> > 目前遇到的情况是：手动“停止录制”后，即使我同时关闭了“监控”按钮，一会又自动开启了录制，需要再手动“停止录制”一次。

已经汇总到 需求列表去了 故进行关闭
2和3要做的工作量有点大 会评估后加入  1 4 5已确定会加入
