### ISSUE TITLE
[需求] 关于主播连线的记录 

### ISSUE THREAD

**Issue by MODOUser** [OriX6/liveRecordAuto#16]
有很多唱歌主播经常会去别人直播间连线，可能是聊天室无画面的那种，在手机上显示的话是有8个位置，能听见每个人说话的声音，也可能是主持人有画面其他人连麦的形式，这种直播能录下来吗？我看好像基本上没有直播软件能录这个东西，如果很难做到的话就算啦，感谢大佬
![屏幕截图 2023-09-24 121320](https://github.com/OriX6/liveRecordAuto/assets/51368808/db219727-8158-4580-9f7f-45f7e41c77f6)
![屏幕截图 2023-09-24 121535](https://github.com/OriX6/liveRecordAuto/assets/51368808/0c45c258-644c-4f81-9e4c-6996ffa28601)

**Comment by OriX6** [comment]
> 有很多唱歌主播经常会去别人直播间连线，可能是聊天室无画面的那种，在手机上显示的话是有8个位置，能听见每个人说话的声音，也可能是主持人有画面其他人连麦的形式，这种直播能录下来吗？我看好像基本上没有直播软件能录这个东西，如果很难做到的话就算啦，感谢大佬 ![屏幕截图 2023-09-24 121320](https://user-images.githubusercontent.com/51368808/270144294-db219727-8158-4580-9f7f-45f7e41c77f6.png) ![屏幕截图 2023-09-24 121535](https://user-images.githubusercontent.com/51368808/270144354-0c45c258-644c-4f81-9e4c-6996ffa28601.png)

我测试了一下，【听潮阁】，录制声音是可以的，录制画面是做不到的。
基于技术角度猜测：
带货主播是有视频输入源的，且是固定输入源
连麦主播的画面是基于抖音的组件动态的，所以录制是黑屏的
暂时没看到有方案能处理，应该是做不到的

**Comment by MODOUser** [comment]
> > 有很多唱歌主播经常会去别人直播间连线，可能是聊天室无画面的那种，在手机上显示的话是有8个位置，能听见每个人说话的声音，也可能是主持人有画面其他人连麦的形式，这种直播能录下来吗？我看好像基本上没有直播软件能录这个东西，如果很难做到的话就算啦，感谢大佬 !
> 
> 我测试了一下，【听潮阁】，录制声音是可以的，录制画面是做不到的。 基于技术角度猜测： 带货主播是有视频输入源的，且是固定输入源 连麦主播的画面是基于抖音的组件动态的，所以录制是黑屏的 暂时没看到有方案能处理，应该是做不到的

好的，感谢大佬的测试
