### ISSUE TITLE
Version 1.0.7 does not work, recording does not start

### ISSUE THREAD

**Issue by AvrilL161** [OriX6/liveRecordAuto#17]
Sorry, I can't write in Chinese. Thank you very much for your work.
Version 1.0.7 does not work, recording does not start. Recording folder is empty. But the program displays that recording is in progress.
And I can't downgrade to the previous version (1.0.6)
![2023-09-24_14-15-26](https://github.com/OriX6/liveRecordAuto/assets/29428522/dfaed09d-41f1-46e6-a5ad-df0de606fa16)

Reinstalling the app, doesn't work
Changing the save folder, doesn't work
Deleting and adding a streamer room, doesn't work

![2023-09-24_14-47-34](https://github.com/OriX6/liveRecordAuto/assets/29428522/ac6a4508-7e9e-4205-b2a2-8b9912d70da7)

Version 1.0.6 worked fine, sometimes didn't finish recording when streamer ended the broadcast.

**Comment by OriX6** [comment]
> Sorry, I can't write in Chinese. Thank you very much for your work. Version 1.0.7 does not work, recording does not start. Recording folder is empty. But the program displays that recording is in progress. And I can't downgrade to the previous version (1.0.6) ![2023-09-24_14-15-26](https://user-images.githubusercontent.com/29428522/270161075-dfaed09d-41f1-46e6-a5ad-df0de606fa16.png)
> 
> Reinstalling the app, doesn't work Changing the save folder, doesn't work Deleting and adding a streamer room, doesn't work
> 
> ![2023-09-24_14-47-34](https://user-images.githubusercontent.com/29428522/270162137-ac6a4508-7e9e-4205-b2a2-8b9912d70da7.png)
> 
> Version 1.0.6 worked fine, sometimes didn't finish recording when streamer ended the broadcast.
Thank you for submitting the issue. After testing, I found that the Douyin platform has just changed its API format today, which caused the failure of retrieving the data source. I will update it immediately.

**Comment by OriX6** [comment]
The issue has been fixed, and it will be resolved with the update in version 1.0.8.

**Comment by AvrilL161** [comment]
> The issue has been fixed, and it will be resolved with the update in version 1.0.8.

Thank you! Version 1.0.8 works fine.
Did you remove the log file from the recording folder? it was possible to track errors with it.

**Comment by OriX6** [comment]
> > The issue has been fixed, and it will be resolved with the update in version 1.0.8.
> 
> Thank you! Version 1.0.8 works fine. Did you remove the log file from the recording folder? it was possible to track errors with it.

Starting from version 1.0.7, I will only throw ffmpeg logs when errors occur, instead of constantly throwing them, which might have been causing some distractions for users.

**Comment by AvrilL161** [comment]
> Starting from version 1.0.7, I will only throw ffmpeg logs when errors occur, instead of constantly throwing them, which might have been causing some distractions for users.

If an ffmpeg error occurs, the log file will be created in the recording folder?

**Comment by OriX6** [comment]
> > Starting from version 1.0.7, I will only throw ffmpeg logs when errors occur, instead of constantly throwing them, which might have been causing some distractions for users.
> 
> If an ffmpeg error occurs, the log file will be created in the recording folder?

Yes, including but not limited to issues with the live source or format encoding. The reason why it didn't throw the logs in your case is due to changes in the interface, which caused the live URL itself to be incorrect. Therefore, ffmpeg did not run because there was no established connection with the incorrect URL. Previously, it would continuously log real-time information, but I believe it is not meaningful and many users have provided feedback that they don't need to see it.

**Comment by AvrilL161** [comment]
> Yes, including but not limited to issues with the live source or format encoding. The reason why it didn't throw the logs in your case is due to changes in the interface, which caused the live URL itself to be incorrect. Therefore, ffmpeg did not run because there was no established connection with the incorrect URL. Previously, it would continuously log real-time information, but I believe it is not meaningful and many users have provided feedback that they don't need to see it.

I like it when there are detailed logs, helps in finding errors. if a log file will be created when errors occur, that’s also not bad.
Thank you again!
