### ISSUE TITLE
1.0.8 快手失效了么

### ISSUE THREAD

**Issue by mybdye** [OriX6/liveRecordAuto#18]
1.0.8 上快手添加id 后不出名字 没法添加

**Comment by OriX6** [comment]
我这边是正常的

如果添加失败大概率是触发了快手的风控  取消快手相关的监控等待一段时间或者重启光猫或者重启软件 暂时还没有能比较完美过这个风控的方法

![微信图片_20230926112319](https://github.com/OriX6/liveRecordAuto/assets/142074786/4c7a92d3-a490-4655-a32e-1e314aeeb767)

**Comment by mybdye** [comment]
了解，回头试下
