### ISSUE TITLE
启动软件后，即使没有添加监控主播，软件还是会有1mb每秒的网速

### ISSUE THREAD

**Issue by wtvue** [OriX6/liveRecordAuto#2]
![QQ截图20230903003414](https://github.com/OriX6/liveRecordAuto/assets/36100538/62d277e3-2f2c-4923-bcee-7a58cc6d4c44)
如图，在没有任何监控直播的情况下，还是会有较高的网络占用。

**Comment by wtvue** [comment]
![QQ截图20230903004214](https://github.com/OriX6/liveRecordAuto/assets/36100538/f4e1f4b5-35cd-46b7-9e4d-440bee0197d5)
附上电脑管家和火绒的流量监控截图

**Comment by OriX6** [comment]
> ![QQ截图20230903004214](https://user-images.githubusercontent.com/36100538/265218670-f4e1f4b5-35cd-46b7-9e4d-440bee0197d5.png) 附上电脑管家和火绒的流量监控截图

持续时间大概是多久啊 ~

**Comment by wtvue** [comment]
一直在持续，我换了一台笔记本（截图是台式机），也会在后台一直跑下载速度。

**Comment by OriX6** [comment]
好的 我这边测试一下

**Comment by t1xhop** [comment]
> 好的 我这边测试一下

请问下如何关闭 录制完自动转码这个功能
