### ISSUE TITLE
初始化数据失败

### ISSUE THREAD

**Issue by asm00681** [OriX6/liveRecordAuto#29]
打开软件显示
初始化数据失败,请重启软件或者联系作者,具体错误:Unexpected token '', ""... is not valid JSON

**Comment by OriX6** [comment]
> 打开软件显示 初始化数据失败,请重启软件或者联系作者,具体错误:Unexpected token '', ""... is not valid JSON

请尝试删除 C:\Users\【你的用户名】\AppData\Roaming\live_record_auto_nian\db 文件夹下的 db.json
你的data文件被篡改了

**Comment by asm00681** [comment]
刪除後成功開啟了，感謝
