### ISSUE TITLE
录制中断/监控失败 bug

### ISSUE THREAD

**Issue by LeoYanlv** [OriX6/liveRecordAuto#3]
1、监控没有成功过，只能手动刷新才能录制
2、录制经常中断，录制的全是小文件

![屏幕截图 2023-09-04 195251](https://github.com/OriX6/liveRecordAuto/assets/39099622/17551acf-6d50-4de4-bbef-ee0c36d162a3)

**Comment by OriX6** [comment]
> 1、监控没有成功过，只能手动刷新才能录制 2、录制经常中断，录制的全是小文件
> 
> ![屏幕截图 2023-09-04 195251](https://user-images.githubusercontent.com/39099622/265451363-17551acf-6d50-4de4-bbef-ee0c36d162a3.png)

监控没成功 大概率是ip被ban了  请更换ip  重启光猫
细碎是本视频流损坏了  这个bug已经记录了 暂时还在思考怎么比较好的去修复

**Comment by LeoYanlv** [comment]
用这个软件自动监控就没问题，也不会断，只是只能监控3个用户
![屏幕截图 2023-09-05 090650](https://github.com/OriX6/liveRecordAuto/assets/39099622/1d5e5d3a-6191-49da-aeb0-4434d092e3e1)

**Comment by OriX6** [comment]
> 用这个软件自动监控就没问题，也不会断，只是只能监控3个用户 ![屏幕截图 2023-09-05 090650](https://user-images.githubusercontent.com/39099622/265558190-1d5e5d3a-6191-49da-aeb0-4434d092e3e1.png)

嗯 你这边用我这个软件的话单次监控多少个呢？
断的问题需要检测流的稳定性然后自动切换

**Comment by esouxcon** [comment]
![2023-09-09_001646](https://github.com/OriX6/liveRecordAuto/assets/120587338/237225d5-9db5-491b-94be-2c6bd6e099be)
这个软体嘛.. 有时候也是会录制小文件
流的稳定性有时确时会有问题 不一定是软件的问题

**Comment by OriX6** [comment]
1.0.9 已发布 同类型的问题比较多 汇总后本issue close
