### ISSUE TITLE
关于主播名字存在不能新建文件夹的情况

### ISSUE THREAD

**Issue by leolovehua** [OriX6/liveRecordAuto#32]
直播录屏出现主播名字如果包含了文件夹名字不可使用的符号，就会出现录屏没办法写入文件出来，可以考虑把文件名使用设置中的备注那里名称，这样就不会出现相类似的问题了。希望可以修改下该功能。
![image](https://github.com/OriX6/liveRecordAuto/assets/147321659/07d4af42-b4af-43e8-86ca-f81947afc7f5)

**Comment by OriX6** [comment]
> 直播录屏出现主播名字如果包含了文件夹名字不可使用的符号，就会出现录屏没办法写入文件出来，可以考虑把文件名使用设置中的备注那里名称，这样就不会出现相类似的问题了。希望可以修改下该功能。 ![image](https://user-images.githubusercontent.com/147321659/273450416-07d4af42-b4af-43e8-86ca-f81947afc7f5.png)

请提供一下主播名字或者特殊的符号 我好直接正则替换

**Comment by OriX6** [comment]
1.0.9已发布 请重新尝试
