### ISSUE TITLE
配置修改不了

### ISSUE THREAD

**Issue by yalik01** [OriX6/liveRecordAuto#33]
第一次可以修改，第二次以后确认并修改按钮变灰，有时第一次也不能修改。另外建议把软件做成绿色便携版，这样重装系统或者复制到别的电脑也不用重新设置软件。
![屏幕截图 2023-10-10 085138](https://github.com/OriX6/liveRecordAuto/assets/94151038/c7be9217-e2c2-4041-9d03-17abc301db8d)

**Comment by OriX6** [comment]
> 第一次可以修改，第二次以后确认并修改按钮变灰，有时第一次也不能修改。另外建议把软件做成绿色便携版，这样重装系统或者复制到别的电脑也不用重新设置软件。 ![屏幕截图 2023-10-10 085138](https://user-images.githubusercontent.com/94151038/273745830-c7be9217-e2c2-4041-9d03-17abc301db8d.jpg)

- 这个是现存bug，将会在下个版本fix掉

**Comment by OriX6** [comment]
1.0.9已发布 本issue close
