### ISSUE TITLE
[求助]今天照常开始录制后，保存目录内无任何文件生成

### ISSUE THREAD

**Issue by hanc44** [OriX6/liveRecordAuto#36]
抖音连续每天对同一个主播进行录制，今天用本地网络录制时，软件一切正常，但是文件夹内无任何文件生成，停止录制等待1~5秒依然是空的。
然后挂上VPN再进行录制后，文件夹内成功出现.ts文件。
这是我本地的IP被风控了吗？请教如何解决
另外，大大能否考虑增加一个是否成功开始录制的判断，如果没有去检查文件夹就无法发现问题，感谢！

**Comment by OriX6** [comment]
> 抖音连续每天对同一个主播进行录制，今天用本地网络录制时，软件一切正常，但是文件夹内无任何文件生成，停止录制等待1~5秒依然是空的。 然后挂上VPN再进行录制后，文件夹内成功出现.ts文件。 这是我本地的IP被风控了吗？请教如何解决 另外，大大能否考虑增加一个是否成功开始录制的判断，如果没有去检查文件夹就无法发现问题，感谢！

你是总共检测了多少个助播啊

**Comment by hanc44** [comment]
> > 抖音连续每天对同一个主播进行录制，今天用本地网络录制时，软件一切正常，但是文件夹内无任何文件生成，停止录制等待1~5秒依然是空的。 然后挂上VPN再进行录制后，文件夹内成功出现.ts文件。 这是我本地的IP被风控了吗？请教如何解决 另外，大大能否考虑增加一个是否成功开始录制的判断，如果没有去检查文件夹就无法发现问题，感谢！
> 
> 你是总共检测了多少个助播啊

就一个呀，每天都同一时间同一个主播录制

**Comment by OriX6** [comment]
1.0.9已发布请重试
