### ISSUE TITLE
【求助】打开软件显示：“初始化数据失败,请重启软件或者联系作者,具体错误:Unexpected token '', ""... is not valid JSON”

### ISSUE THREAD

**Issue by btg12** [OriX6/liveRecordAuto#37]
打开软件显示：“初始化数据失败,请重启软件或者联系作者,具体错误:Unexpected token '', ""... is not valid JSON”，
之前也没有这种情况，不管关闭重新打开还是重新下载安装都不行，求助作者大大怎么办
![image](https://github.com/OriX6/liveRecordAuto/assets/147799918/fc2b3f66-8dfb-4cdb-ba0e-182f10e4b59f)

**Comment by OriX6** [comment]
> 打开软件显示：“初始化数据失败,请重启软件或者联系作者,具体错误:Unexpected token '', ""... is not valid JSON”， 之前也没有这种情况，不管关闭重新打开还是重新下载安装都不行，求助作者大大怎么办 ![image](https://user-images.githubusercontent.com/147799918/274817614-fc2b3f66-8dfb-4cdb-ba0e-182f10e4b59f.png)

请参考
https://github.com/OriX6/liveRecordAuto/issues/29

**Comment by patrick-HX** [comment]
我也提示这个，不知道咋办了

**Comment by anddca** [comment]
我今天也有这个提示哦，而且#29的方案解决不了哦！大佬！
![微信图片_20240216122707](https://github.com/OriX6/liveRecordAuto/assets/160203204/363bae2f-3a1f-4624-b8c4-925b4de759ea)
