### ISSUE TITLE
[建议] 能否等输完id/链接后手动点击查询呢

### ISSUE THREAD

**Issue by mybdye** [OriX6/liveRecordAuto#40]
每次手动输id ，刚输入两就提示检查格式，光标又不会重新聚焦在输入框

**Comment by OriX6** [comment]
> 每次手动输id ，刚输入两就提示检查格式，光标又不会重新聚焦在输入框

大部分用户需要这个功能。关于你说的我会增加防抖的等待时间，目前可能时间太短了，下个版本调整

**Comment by OriX6** [comment]
已经添加到TODO中，本issue close
