### ISSUE TITLE
[BUG] 初始化数据失败,请重启软件或者联系作者,具体错误:Unexpected token '', ""... is not valid JSON

### ISSUE THREAD

**Issue by Gauziness** [OriX6/liveRecordAuto#42]
今天上午电脑一直开着，软件挂在后台，下午的时候电脑长时间待机自动关机了，我开机之后打开软件就出现了这个，再次重启软件还是这个问题，重启电脑问题也还是没有解决。
![2023-10-16](https://github.com/OriX6/liveRecordAuto/assets/148053737/b3117ec7-8188-4aa8-a4ac-a7ad4e9ebcda)

**Comment by OriX6** [comment]
> 今天上午电脑一直开着，软件挂在后台，下午的时候电脑长时间待机自动关机了，我开机之后打开软件就出现了这个，再次重启软件还是这个问题，重启电脑问题也还是没有解决。 ![2023-10-16](https://user-images.githubusercontent.com/148053737/275452656-b3117ec7-8188-4aa8-a4ac-a7ad4e9ebcda.png)

参考 https://github.com/OriX6/liveRecordAuto/issues/29    用于储存数据的data文件被篡改，导致解析异常，初始化失败
