### ISSUE TITLE
请问可以录制直播时的弹幕嘛？

### ISSUE THREAD

**Issue by zihaoxingstudy1** [OriX6/liveRecordAuto#44]
请问可以录制直播时的弹幕吗？

**Comment by OriX6** [comment]
> 请问可以录制直播时的弹幕吗？

这个需求之前有人提了，不过优先级较低

**Comment by zihaoxingstudy1** [comment]
> > 请问可以录制直播时的弹幕吗？
> 
> 这个需求之前有人提了，不过优先级较低

哦哦，好的

**Comment by lxr760** [comment]
> > 请问可以录制直播时的弹幕吗？
> 
> 这个需求之前有人提了，不过优先级较低

评论跟弹幕是一回事吗？  能不能像手机录屏那样把评论也录下

**Comment by OriX6** [comment]
> > > 请问可以录制直播时的弹幕吗？
> > 
> > 
> > 这个需求之前有人提了，不过优先级较低
> 
> 评论跟弹幕是一回事吗？ 能不能像手机录屏那样把评论也录下

评论又是啥
如果你说的是直播间的公屏评论，那就是弹幕

**Comment by Gh-37** [comment]
> > 请问可以录制直播时的弹幕吗？
> 
> 这个需求之前有人提了，不过优先级较低

我也希望有这个功能👍

**Comment by CoolYoungAllen** [comment]
感谢作者的分享，同样强烈需求录制直播评论（弹幕）！
