### ISSUE TITLE
作者麻烦看一下

### ISSUE THREAD

**Issue by 23clot** [OriX6/liveRecordAuto#5]
1.希望gui界面可以大小调节
2.能不能做一个录制中 可以看直播画面的功能
3.能不能做一个抖音号主页就可以添加的缓存队列
4。文件格式可以改 热衷于ts

**Comment by OriX6** [comment]
> 1.希望gui界面可以大小调节 2.能不能做一个录制中 可以看直播画面的功能 3.能不能做一个抖音号主页就可以添加的缓存队列 4。文件格式可以改 热衷于ts

1.这个会影响到整体的布局 不太想写自适应
2.这个要赛个播放器进去 可能暂时不考虑 后期会考虑加进去但是整个包的大小会变更 理论上可以边录边播
3.主页是支持的 只是未开播的不支持 （未开播获取房间信息的接口需要登录）
4.ts或者fmp4 格式抗损坏性更强  目前只考虑这两个格式录制  最终成为什么格式 其实可以走转码工具 当然后期也许会增加一个选项 不过可选的可能就是 ts/mp4

**Comment by 23clot** [comment]
3。未开播添加用户可以升级一下吗  需要登陆也没关系🥺

**Comment by SkyLI10** [comment]
想问一下作者，会供相互交流与学习公布源码吗？或者以后也会收费吗？谢谢

**Comment by OriX6** [comment]
> 想问一下作者，会供相互交流与学习公布源码吗？或者以后也会收费吗？谢谢

公布源码应该不会考虑 
永久免费（如果不吃函的话）

**Comment by iapeng** [comment]
能设置时长，或录制完毕后关机，就好了
