### ISSUE TITLE
程序崩了，感谢兄弟发的程序。留个地址给你寄点特产

### ISSUE THREAD

**Issue by like1053** [OriX6/liveRecordAuto#57]
/
![QQ截图20231101021625](https://github.com/OriX6/liveRecordAuto/assets/144716455/eda00118-99e2-4fa1-bab2-59a9d66335a9)

**Comment by Dreamfzkj** [comment]
谁能联系上作者大大

**Comment by asm00681** [comment]
我也试过，删一个文件可解决

**Comment by like1053** [comment]
兄弟删除什么文件

**Comment by wugan2003** [comment]
我也是同样的问题
