### ISSUE TITLE
作者您好，我的软件无法正常打开

### ISSUE THREAD

**Issue by wugan2003** [OriX6/liveRecordAuto#61]
今天无法正常打开，不知道是大家都遇到这样的问题，还是我这边的特例，希望可以得到解决，给大佬点个赞！
![微信截图_20231108080308](https://github.com/OriX6/liveRecordAuto/assets/150202031/8af5f742-b570-4798-8668-7ca65e9e807c)

**Comment by SkyLI10** [comment]
我今天也出现这种情况

**Comment by SkyLI10** [comment]
解决方法：
C:\Users\你的用户名\AppData\Roaming\live_record_auto_nian\db这个程序数据目录下，删掉主播数据文件db.json，然后把主播全部重新加一遍生成新的数据库文件就可以了

**Comment by why3316** [comment]
> 解决方法： C:\Users\你的用户名\AppData\Roaming\live_record_auto_nian\db这个程序数据目录下，删掉主播数据文件db.json，把主播全部重新加上然后生成新的数据库文件就可以了

谢谢，我也出现这种情况，用你的方法，完美解决。
