### ISSUE TITLE
录制某些直播间视频会分成好多文件，但有些直播间又不会

### ISSUE THREAD

**Issue by lxr760** [OriX6/liveRecordAuto#64]
如果，这个直播间直播时候是一直没断的，但是录制的文件分成了好多部分，甚至有些文件非常小
![Snipaste_2023-11-15_19-02-51](https://github.com/OriX6/liveRecordAuto/assets/8476457/32bc505b-8c60-4fa8-a144-f1b008e55b73)

我怀疑是IP被封控了，于是在同一个电脑保持外网IP不变，长时间录制的另外一个直播间的视频，连续录制了有10多个小时，只产生了一个文件，大小60G,看起来又不像是被风控
![Snipaste_2023-11-15_19-03-41](https://github.com/OriX6/liveRecordAuto/assets/8476457/dda36a91-d388-4a57-8aec-33cd77846d56)

**Comment by OriX6** [comment]
参考 https://github.com/OriX6/liveRecordAuto/issues/98
