### ISSUE TITLE
建议默认设置不转码和自动关机选项

### ISSUE THREAD

**Issue by iapeng** [OriX6/liveRecordAuto#72]
一般当录制都是没在电脑前观看，时间长了，经常遇到网络不稳定情况。建议：
1、不用转码，什么时间网络断了，前面的视频都存在。ts、flv都，都能直播播放，为何要转成mp4呢
2、录制完成后，电脑自动关机，或者，定时关机。

**Comment by OriX6** [comment]
> 一般当录制都是没在电脑前观看，时间长了，经常遇到网络不稳定情况。建议： 1、不用转码，什么时间网络断了，前面的视频都存在。ts、flv都，都能直播播放，为何要转成mp4呢 2、录制完成后，电脑自动关机，或者，定时关机。

1已处理，2暂时不考虑
