### ISSUE TITLE
安装好后打开错误

### ISSUE THREAD

**Issue by 2duat** [OriX6/liveRecordAuto#8]
![360截图168102279897109](https://github.com/OriX6/liveRecordAuto/assets/65028966/d2ce6de9-87a7-48c6-99df-ea6269a3d42c)

**Comment by OriX6** [comment]
> ![360截图168102279897109](https://user-images.githubusercontent.com/65028966/267319008-d2ce6de9-87a7-48c6-99df-ea6269a3d42c.png)

这个问题是你的F盘没有创建文件夹的权限
我的代码初始化会把本地磁盘剩余空间最多的磁盘作为初始目录
请检查F盘是不是映射网盘或者其他
下个版本会做一个兼容性处理

**Comment by OriX6** [comment]
1.0.7已经优化修复了
