### ISSUE TITLE
【常见问题】遇到 “初始化数据失败” 错误的可以看我这里

### ISSUE THREAD

**Issue by uswei11** [OriX6/liveRecordAuto#94]
将安装目录下的db文件夹下的db.json删除了，再重新打开一遍就好了。
![image](https://github.com/OriX6/liveRecordAuto/assets/90755134/d2ee87ad-6d26-400e-a509-4c4ca3a6055b)

**Comment by frew112** [comment]
没有这个文件夹

**Comment by frew112** [comment]
![Uploading 423421.jpg…]()

**Comment by OriX6** [comment]
请看清 是**Roaming**文件夹下

**Comment by frew112** [comment]
> 请看清 是**Roaming**文件夹下 详细路径 C:\Users\【你的用户名】\AppData\Roaming\live_record_auto_nian\db 文件夹下的 db.json

嗷嗷，谢谢，我的问题，没看仔细。问题已解决了。（话说录制的视频都是一段一段的怎么回事呀？不自动转码是不是就不会这样了？）

**Comment by OriX6** [comment]
1.1.2 已增加自动重置 故关闭
