### ISSUE TITLE
遇到 “初始化数据失败” 错误，却又没有各位大佬说的DB文件夹

### ISSUE THREAD

**Issue by liu2153** [OriX6/liveRecordAuto#97]
![微信截图_20240226152902](https://github.com/OriX6/liveRecordAuto/assets/42597841/94a04e7e-030b-42f6-a626-d8ad371567b8)

**Comment by OriX6** [comment]
目录错了  C:\Users\【你的用户名】\AppData\Roaming\live_record_auto_nian\db 文件夹下的 db.json  是Roaming目录
