### ISSUE TITLE
2个小问题，一是更新1.1.1后仍无法添加快手，添加快手主播一直提示风控什么的。第二个是请问会不会考虑增加开播提醒功能

### ISSUE THREAD

**Issue by douying2334** [OriX6/liveRecordAuto#99]
昨天更新终于可以倒计时同意就不用每次点了 太好了

**Comment by OriX6** [comment]
- 快手测试没有碰到风控情况，双接口都通过了。你得看看本地监控的数量是否过多，快手风控力度比较强
- 开播提醒暂时还没考虑到排期内

**Comment by OriX6** [comment]
> 昨天更新终于可以倒计时同意就不用每次点了 太好了

- 快手测试没有碰到风控情况，双接口都通过了。你得看看本地监控的数量是否过多，快手风控力度比较强
- 开播提醒暂时还没考虑到排期内

**Comment by OriX6** [comment]
1.1.3快手又增加了一个接口 请尝试测试
